# Generated by Django 4.2.1 on 2023-05-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_roles_user_type_alter_user_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher'), ('SUPERVISOR', 'supervisor'), ('ADMIN', 'admin')], default='STUDENT', max_length=50),
        ),
    ]
