# Generated by Django 4.2.1 on 2023-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher')], default='student', max_length=50),
        ),
    ]
