# Generated by Django 4.2.1 on 2023-05-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_category_description'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='category_course', to='common.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
                ('is_public', models.BooleanField(choices=[('0', False), ('1', True)])),
                ('time', models.TimeField(auto_now_add=True)),
                ('position', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='course.course')),
            ],
        ),
    ]
