# Generated by Django 4.2.1 on 2023-05-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='category',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
