# Generated by Django 4.2.1 on 2023-05-19 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='course',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='is_answer',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='common.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
