# Generated by Django 4.2.1 on 2023-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_contactform_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/images')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram')], default=None, max_length=100)),
                ('urls', models.URLField()),
            ],
        ),
    ]
