# Generated by Django 4.2.1 on 2023-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_socialmedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram')], default='', max_length=100),
        ),
    ]
