# Generated by Django 4.2.1 on 2023-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_socialmedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram')], default='', max_length=100, unique=True),
        ),
    ]
