# Generated by Django 4.2.1 on 2023-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_socialmedia_name_alter_socialmedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
